function drawBackground(){
 const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#071225');g.addColorStop(.58,'#111833');g.addColorStop(1,'#130d21');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);
 ctx.save();ctx.globalAlpha=.7;for(const s of stars){const x=((s.x*W)-camX*.02)%W;ctx.fillStyle=`rgba(210,225,255,${s.a})`;ctx.beginPath();ctx.arc((x+W)%W,s.y*H,s.r,0,Math.PI*2);ctx.fill()}ctx.restore();
 ctx.save();ctx.globalAlpha=.65;const mx=W*.78-camX*.015;const my=H*.18;const rg=ctx.createRadialGradient(mx,my,4,mx,my,70);rg.addColorStop(0,'rgba(220,235,255,.9)');rg.addColorStop(.35,'rgba(156,163,255,.28)');rg.addColorStop(1,'rgba(90,70,180,0)');ctx.fillStyle=rg;ctx.beginPath();ctx.arc(mx,my,72,0,Math.PI*2);ctx.fill();ctx.restore();
 for(let layer=0;layer<3;layer++){const base=H*.62+layer*42,amp=44+layer*16,speed=.08+layer*.05;ctx.beginPath();ctx.moveTo(0,H);for(let x=0;x<=W+40;x+=40){const wx=x+camX*speed;const y=base+Math.sin(wx*.0018+layer)*amp+Math.sin(wx*.0041)*amp*.25;ctx.lineTo(x,y)}ctx.lineTo(W,H);ctx.closePath();ctx.fillStyle=layer===0?'#0b1730':layer===1?'#11172d':'#16152c';ctx.fill()}
}
function drawWorld(){
 ctx.save();const sx=shake?rand(-shake,shake):0,sy=shake?rand(-shake*.5,shake*.5):0;ctx.translate(-camX+sx,sy);
 const gg=ctx.createLinearGradient(0,floorY,0,H);gg.addColorStop(0,'#29243d');gg.addColorStop(1,'#0d0c18');ctx.fillStyle=gg;ctx.fillRect(0,floorY,worldW,H-floorY+160);ctx.fillStyle='rgba(139,92,246,.16)';ctx.fillRect(0,floorY,worldW,4);
 for(const d of decor)drawDecor(d);
 for(const p of platforms){if(p.type==='ground')continue;ctx.fillStyle='#2d2a43';roundRect(ctx,p.x,p.y,p.w,p.h,7);ctx.fill();ctx.fillStyle='rgba(126,97,190,.26)';ctx.fillRect(p.x,p.y,p.w,4)}
 for(const e of enemies)if(!e.dead)drawEnemy(e);
 drawPlayer();
 for(const p of projectiles)drawProjectile(p);
 for(const p of particles){ctx.globalAlpha=clamp(p.life/p.max,0,1);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.size*(.5+.5*p.life/p.max),0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;
 ctx.restore();
 if(flash>0){ctx.fillStyle=`rgba(255,255,255,${flash})`;ctx.fillRect(0,0,W,H)}
}
function roundRect(c,x,y,w,h,r){r=Math.min(r,w/2,h/2);c.beginPath();c.moveTo(x+r,y);c.arcTo(x+w,y,x+w,y+h,r);c.arcTo(x+w,y+h,x,y+h,r);c.arcTo(x,y+h,x,y,r);c.arcTo(x,y,x+w,y,r);c.closePath()}
function drawDecor(d){
 if(d.type==='crystal'){ctx.save();ctx.translate(d.x,floorY);ctx.scale(d.s,d.s);ctx.fillStyle='rgba(61,28,110,.32)';ctx.beginPath();ctx.ellipse(0,7,34,10,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#5b4b8a';ctx.beginPath();ctx.moveTo(-14,0);ctx.lineTo(-4,-55);ctx.lineTo(8,0);ctx.closePath();ctx.fill();ctx.fillStyle='#8367c7';ctx.beginPath();ctx.moveTo(3,0);ctx.lineTo(17,-36);ctx.lineTo(25,0);ctx.closePath();ctx.fill();ctx.restore()}
 else if(d.type==='ruin'){ctx.save();ctx.translate(d.x,floorY);ctx.scale(d.s,d.s);ctx.fillStyle='#26233a';ctx.fillRect(-12,-65,24,65);ctx.fillRect(-25,-65,50,10);ctx.fillStyle='rgba(139,92,246,.18)';ctx.fillRect(-8,-50,4,26);ctx.restore()}
 else if(d.type==='gate'){ctx.save();ctx.translate(d.x,floorY);ctx.scale(d.s,d.s);ctx.strokeStyle='#39334f';ctx.lineWidth=20;ctx.beginPath();ctx.arc(0,-75,62,Math.PI,Math.PI*2);ctx.lineTo(62,0);ctx.moveTo(-62,-75);ctx.lineTo(-62,0);ctx.stroke();const rg=ctx.createRadialGradient(0,-58,6,0,-58,55);rg.addColorStop(0,'rgba(103,232,249,.75)');rg.addColorStop(.45,'rgba(139,92,246,.5)');rg.addColorStop(1,'rgba(139,92,246,0)');ctx.fillStyle=rg;ctx.beginPath();ctx.arc(0,-58,58,0,Math.PI*2);ctx.fill();ctx.restore()}
}
function drawPlayer(){const p=player;ctx.save();ctx.translate(p.x+p.w/2,p.y+p.h/2);if(p.dir<0)ctx.scale(-1,1);if(p.inv>0&&Math.floor(p.inv*18)%2===0)ctx.globalAlpha=.45;const glow=ctx.createRadialGradient(7,-2,1,7,-2,34);glow.addColorStop(0,'rgba(103,232,249,.28)');glow.addColorStop(1,'rgba(103,232,249,0)');ctx.fillStyle=glow;ctx.beginPath();ctx.arc(7,-2,34,0,Math.PI*2);ctx.fill();ctx.fillStyle='#151a2e';roundRect(ctx,-15,-6,30,36,11);ctx.fill();ctx.fillStyle='#6d56b3';ctx.beginPath();ctx.moveTo(-14,5);ctx.lineTo(-26,32);ctx.lineTo(5,28);ctx.closePath();ctx.fill();ctx.fillStyle='#e9d5ff';ctx.beginPath();ctx.arc(1,-16,12,0,Math.PI*2);ctx.fill();ctx.fillStyle='#231a38';ctx.beginPath();ctx.arc(1,-18,12,Math.PI,Math.PI*2);ctx.fill();ctx.fillStyle='#67e8f9';ctx.beginPath();ctx.arc(6,-17,2.3,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#c4b5fd';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(10,5);ctx.lineTo(27,-8);ctx.stroke();ctx.fillStyle='#67e8f9';ctx.beginPath();ctx.arc(29,-10,5,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawEnemy(e){ctx.save();ctx.translate(e.x+e.w/2,e.y+e.h/2);if(e.hit>0)ctx.globalAlpha=.55;if(e.type==='wisp'){const rg=ctx.createRadialGradient(0,0,2,0,0,24);rg.addColorStop(0,'#f0abfc');rg.addColorStop(.35,'#8b5cf6');rg.addColorStop(1,'rgba(139,92,246,0)');ctx.fillStyle=rg;ctx.beginPath();ctx.arc(0,0,24,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(5,-2,3,0,Math.PI*2);ctx.fill()}else if(e.type==='crawler'){ctx.fillStyle='#44263f';ctx.beginPath();ctx.ellipse(0,5,25,15,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fb7185';ctx.lineWidth=3;for(let i=-1;i<=1;i+=2){ctx.beginPath();ctx.moveTo(i*8,10);ctx.lineTo(i*19,23);ctx.stroke()}ctx.fillStyle='#fda4af';ctx.fillRect(8,1,5,3)}else if(e.type==='sentinel'){ctx.fillStyle='#31314b';roundRect(ctx,-20,-30,40,60,10);ctx.fill();ctx.fillStyle='#8b5cf6';ctx.fillRect(-12,-18,24,4);ctx.strokeStyle='#6b5c93';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-16,17);ctx.lineTo(-27,31);ctx.moveTo(16,17);ctx.lineTo(27,31);ctx.stroke()}else{const rg=ctx.createRadialGradient(0,-15,4,0,-15,70);rg.addColorStop(0,'rgba(251,191,36,.18)');rg.addColorStop(1,'rgba(139,92,246,0)');ctx.fillStyle=rg;ctx.beginPath();ctx.arc(0,-15,72,0,Math.PI*2);ctx.fill();ctx.fillStyle='#241b35';roundRect(ctx,-42,-52,84,104,18);ctx.fill();ctx.fillStyle='#5b3b79';ctx.beginPath();ctx.moveTo(-40,-28);ctx.lineTo(-62,-4);ctx.lineTo(-35,5);ctx.closePath();ctx.fill();ctx.beginPath();ctx.moveTo(40,-28);ctx.lineTo(62,-4);ctx.lineTo(35,5);ctx.closePath();ctx.fill();ctx.fillStyle='#fbbf24';ctx.fillRect(-17,-23,12,5);ctx.fillRect(5,-23,12,5);ctx.fillStyle='#8b5cf6';ctx.fillRect(-25,25,50,5)}ctx.restore();if(e.hp<e.maxHp){const bw=e.type==='boss'?140:e.w,bx=e.x+e.w/2-bw/2,by=e.y-13;ctx.fillStyle='rgba(0,0,0,.42)';ctx.fillRect(bx,by,bw,5);ctx.fillStyle=e.type==='boss'?'#fbbf24':'#fb7185';ctx.fillRect(bx,by,bw*clamp(e.hp/e.maxHp,0,1),5)}}
function drawProjectile(p){ctx.save();const rg=ctx.createRadialGradient(p.x,p.y,1,p.x,p.y,p.r*2.4);if(p.type==='bolt'){rg.addColorStop(0,'#fff');rg.addColorStop(.2,'#67e8f9');rg.addColorStop(.58,'#8b5cf6');rg.addColorStop(1,'rgba(139,92,246,0)')}else{rg.addColorStop(0,'#fff');rg.addColorStop(.25,'#fb7185');rg.addColorStop(1,'rgba(251,113,133,0)')}ctx.fillStyle=rg;ctx.beginPath();ctx.arc(p.x,p.y,p.r*2.4,0,Math.PI*2);ctx.fill();ctx.restore()}
function formatTime(s){const m=Math.floor(s/60),sec=Math.floor(s%60);return `${m}:${String(sec).padStart(2,'0')}`}
function bestRunText(){try{const b=JSON.parse(localStorage.getItem('arcaneRiftBest')||'null');if(!b)return 'Best run: not yet recorded';return `Best clear: ${formatTime(b.time)} · Level ${b.level} · ${b.kills} kills`}catch(e){return 'Best run: local save unavailable'}}
function saveBestRun(){try{const old=JSON.parse(localStorage.getItem('arcaneRiftBest')||'null'),next={time:runTime,level:player.level,kills};if(!old||next.time<old.time)localStorage.setItem('arcaneRiftBest',JSON.stringify(next))}catch(e){}}
function setPause(on,manual=false){if(!started||won)return;paused=on;manualPause=manual&&on;ui.pauseSheet.classList.toggle('hidden',!on);Object.keys(keys).forEach(k=>keys[k]=false)}
function draw(){drawBackground();drawWorld()}
function loop(t){const dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
function press(act,on){keys[act]=on;if(act==='jump'&&on&&started&&!paused){keys.jump=true;setTimeout(()=>keys.jump=false,120)}if(act==='cast'&&!on)keys.cast=false;if(act==='dash'&&on){keys.dash=true;setTimeout(()=>keys.dash=false,80)}}
document.querySelectorAll('.touch').forEach(b=>{const act=b.dataset.act;const on=e=>{e.preventDefault();b.classList.add('active');press(act,true)};const off=e=>{e.preventDefault();b.classList.remove('active');press(act,false)};b.addEventListener('pointerdown',on);b.addEventListener('pointerup',off);b.addEventListener('pointercancel',off);b.addEventListener('pointerleave',off)});
window.addEventListener('keydown',e=>{if(['ArrowLeft','a','A'].includes(e.key))keys.left=true;if(['ArrowRight','d','D'].includes(e.key))keys.right=true;if(['ArrowUp','w','W',' '].includes(e.key)){if(!e.repeat)keys.jump=true}if(['j','J'].includes(e.key))keys.cast=true;if(['k','K'].includes(e.key)&&!e.repeat)keys.nova=true;if(e.key==='Shift'&&!e.repeat)keys.dash=true});
window.addEventListener('keyup',e=>{if(['ArrowLeft','a','A'].includes(e.key))keys.left=false;if(['ArrowRight','d','D'].includes(e.key))keys.right=false;if(['ArrowUp','w','W',' '].includes(e.key))keys.jump=false;if(['j','J'].includes(e.key))keys.cast=false;if(e.key==='Shift')keys.dash=false});
document.getElementById('startBtn').addEventListener('click',()=>{initAudio();if(audio.ctx&&audio.ctx.state==='suspended')audio.ctx.resume();startMusic();ui.overlay.classList.add('hidden');ui.pauseSheet.classList.add('hidden');resetGame();if(screen.orientation&&screen.orientation.lock)screen.orientation.lock('landscape').catch(()=>{})});
ui.runStats.textContent=bestRunText();
document.getElementById('pauseBtn').addEventListener('click',()=>setPause(true,true));
document.getElementById('resumeBtn').addEventListener('click',()=>setPause(false,false));
document.getElementById('restartBtn').addEventListener('click',()=>{ui.pauseSheet.classList.add('hidden');resetGame()});
document.getElementById('installBtn').addEventListener('click',()=>ui.installSheet.classList.remove('hidden'));
document.getElementById('installDone').addEventListener('click',()=>ui.installSheet.classList.add('hidden'));
document.addEventListener('visibilitychange',()=>{if(document.hidden&&started&&!paused&&!won){paused=true}else if(!document.hidden&&started&&paused&&!manualPause&&!won){paused=false;last=performance.now()}});
window.addEventListener('blur',()=>{Object.keys(keys).forEach(k=>keys[k]=false)});
if('serviceWorker' in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});
window.addEventListener('contextmenu',e=>e.preventDefault());
