(() => {
'use strict';
try {
const $=s=>document.querySelector(s);
const canvas=$('#application'),boot=$('#boot'),bootCopy=$('#boot-copy'),menu=$('#menu'),brief=$('#brief'),hud=$('#hud'),controls=$('#mobile-controls'),result=$('#result');
const style=document.createElement('style');style.textContent=`
.nav-hint{position:fixed;left:50%;top:max(76px,calc(env(safe-area-inset-top) + 58px));transform:translateX(-50%);z-index:9;display:grid;grid-template-columns:auto auto auto;gap:9px;align-items:center;padding:7px 10px;border-radius:10px;font-size:11px;letter-spacing:.08em;pointer-events:none;background:rgba(3,9,12,.68);border:1px solid rgba(120,220,230,.18)}
.nav-hint b{color:#dce8eb;font-size:10px}.nav-hint span{color:#74d9e6;font-weight:800}.nav-hint small{display:inline-block;color:#ffb34c;font-size:15px;transform-origin:50% 50%}
.interact-prompt{position:fixed;left:50%;bottom:calc(env(safe-area-inset-bottom) + 156px);transform:translateX(-50%);z-index:10;padding:9px 13px;border-radius:8px;background:rgba(2,12,16,.88);border:1px solid rgba(91,221,235,.65);color:#dffcff;font-size:11px;font-weight:800;letter-spacing:.08em;white-space:nowrap;pointer-events:none;box-shadow:0 0 24px rgba(45,200,218,.18)}
.reload-progress{position:fixed;left:50%;bottom:calc(env(safe-area-inset-bottom) + 137px);transform:translateX(-50%);z-index:10;width:120px;height:4px;border-radius:4px;background:rgba(255,255,255,.12);overflow:hidden;pointer-events:none}.reload-progress span{display:block;height:100%;width:0;background:linear-gradient(90deg,#65d7e7,#f1b154)}
.round-btn.active{border-color:#6ee6f1!important;box-shadow:0 0 0 2px rgba(60,210,230,.18),0 0 22px rgba(60,210,230,.16)!important;color:#dfffff!important}
#look-zone,#move-pad,.fire-btn,.round-btn{touch-action:none;-webkit-user-select:none;user-select:none}
@media(max-width:600px){.nav-hint{top:max(69px,calc(env(safe-area-inset-top) + 51px));padding:6px 9px}.interact-prompt{bottom:calc(env(safe-area-inset-bottom) + 143px);font-size:10px}.reload-progress{bottom:calc(env(safe-area-inset-bottom) + 127px)}}`;
document.head.appendChild(style);
const stage=t=>{if(bootCopy)bootCopy.textContent=t;console.log('[BLACKSITE]',t)};
stage('Renderer online · starting Harbor Yard…');

const app=new pc.Application(canvas,{mouse:new pc.Mouse(canvas),touch:pc.platform.touch?new pc.TouchDevice(canvas):undefined,keyboard:new pc.Keyboard(window)});
app.graphicsDevice.maxPixelRatio=Math.min(devicePixelRatio||1,1.35);
app.setCanvasFillMode(pc.FILLMODE_FILL_WINDOW);app.setCanvasResolution(pc.RESOLUTION_AUTO);app.start();
addEventListener('resize',()=>app.resizeCanvas());document.addEventListener('contextmenu',e=>e.preventDefault());canvas.style.touchAction='none';
app.scene.ambientLight=new pc.Color(.20,.25,.29);
if(app.scene.fog){app.scene.fog.type=pc.FOG_LINEAR;app.scene.fog.color.set(.24,.31,.34);app.scene.fog.start=42;app.scene.fog.end=110}
app.scene.exposure=1;stage('Lighting ready · constructing industrial yard…');

const state={mode:'menu',hp:100,armor:60,stamina:100,ammo:30,reserve:120,reload:0,raidTime:720,shield:0,ads:false,firing:false,fireCd:0,yaw:180,pitch:-2,moveX:0,moveY:0,objective:false,kills:0,flash:0,interact:null,assist:null};
const solids=[],fx=[],enemies=[];
const player=new pc.Entity('Player');app.root.addChild(player);player.setPosition(0,0,24);
const camera=new pc.Entity('Camera');camera.addComponent('camera',{clearColor:new pc.Color(.20,.29,.34),fov:68,nearClip:.04,farClip:150});player.addChild(camera);camera.setLocalPosition(0,1.67,0);
if(camera.camera){camera.camera.toneMapping=pc.TONEMAP_FILMIC;camera.camera.gammaCorrection=pc.GAMMA_SRGB}
const sun=new pc.Entity('Sun');sun.addComponent('light',{type:'directional',color:new pc.Color(1,.78,.58),intensity:2.2,castShadows:true,shadowResolution:1024,shadowBias:.22,normalOffsetBias:.035});sun.setEulerAngles(48,-28,0);app.root.addChild(sun);
const fill=new pc.Entity('Fill');fill.addComponent('light',{type:'directional',color:new pc.Color(.27,.43,.58),intensity:.55,castShadows:false});fill.setEulerAngles(-30,140,0);app.root.addChild(fill);

function mat(name,c,metal=0,gloss=.25){const m=new pc.StandardMaterial();m.name=name;m.diffuse=new pc.Color(...c);m.metalness=metal;m.gloss=gloss;m.useMetalness=true;m.update();return m}
const M={asphalt:mat('wet asphalt',[.16,.18,.18],0,.2),concrete:mat('weathered concrete',[.42,.43,.40],0,.18),dark:mat('painted concrete',[.19,.22,.22],0,.19),steel:mat('galvanized steel',[.31,.34,.34],.65,.42),rust:mat('rusted steel',[.38,.16,.07],.3,.22),red:mat('faded red',[.48,.10,.06],.25,.28),blue:mat('faded blue',[.06,.23,.32],.25,.29),green:mat('faded green',[.12,.28,.18],.22,.27),yellow:mat('safety yellow',[.62,.40,.05],.18,.3),wood:mat('rough wood',[.34,.22,.12],0,.13),cloth:mat('cloth',[.12,.15,.13],0,.08),skin:mat('skin',[.45,.31,.23],0,.18),glow:mat('objective',[.04,.55,.72],.15,.8),glass:mat('glass',[.10,.20,.24],.1,.92)};
M.glow.emissive=new pc.Color(0,.5,.8);M.glow.emissiveIntensity=2;M.glow.update();M.glass.opacity=.48;M.glass.blendType=pc.BLEND_NORMAL;M.glass.depthWrite=false;M.glass.update();
function loadTex(url,material,slot='diffuseMap',tiling=1){app.assets.loadFromUrl(url,'texture',(err,a)=>{if(err||!a?.resource)return;const t=a.resource;t.addressU=t.addressV=pc.ADDRESS_REPEAT;t.minFilter=pc.FILTER_LINEAR_MIPMAP_LINEAR;material[slot]=t;const prop=slot==='diffuseMap'?'diffuseMapTiling':slot==='normalMap'?'normalMapTiling':null;if(prop)material[prop]=new pc.Vec2(tiling,tiling);if(slot==='normalMap')material.bumpiness=.8;material.update()})}
const RAW='https://raw.githubusercontent.com/petroulacl/fps-asset-kit/main/textures/';
loadTex(RAW+'Asphalt023S/Asphalt023S.png',M.asphalt,'diffuseMap',12);loadTex(RAW+'Concrete048/Concrete048.png',M.concrete,'diffuseMap',4);loadTex(RAW+'Metal063/Metal063.png',M.steel,'diffuseMap',3);loadTex(RAW+'Metal063/Metal063_2K-JPG_NormalGL.jpg',M.steel,'normalMap',3);

function addSolid(p,s,pad=0){solids.push({minX:p[0]-s[0]/2-pad,maxX:p[0]+s[0]/2+pad,minZ:p[2]-s[2]/2-pad,maxZ:p[2]+s[2]/2+pad})}
function primitive(name,type,p,s,material,solid=false,rot=null){const e=new pc.Entity(name);e.addComponent('render',{type,castShadows:true,receiveShadows:true});e.render.material=material;e.setPosition(...p);e.setLocalScale(...s);if(rot)e.setEulerAngles(...rot);app.root.addChild(e);if(solid)addSolid(p,s);return e}
const box=(n,p,s,m,solid=false,rot=null)=>primitive(n,'box',p,s,m,solid,rot),cyl=(n,p,s,m,solid=false,rot=null)=>primitive(n,'cylinder',p,s,m,solid,rot),sphere=(n,p,s,m)=>primitive(n,'sphere',p,s,m,false);
function customMesh(name,positions,indices,material,p=[0,0,0]){const g=new pc.Geometry();g.positions=positions;g.indices=indices;g.calculateNormals();const mesh=pc.Mesh.fromGeometry(app.graphicsDevice,g),mi=new pc.MeshInstance(mesh,material);mi.castShadow=mi.receiveShadow=true;const e=new pc.Entity(name);e.addComponent('render',{meshInstances:[mi]});e.setPosition(...p);app.root.addChild(e);return e}
function warehouse(name,x,z,w,d,wallH,roofH){const P=[],cross=[[-w/2,0],[-w/2,wallH],[0,wallH+roofH],[w/2,wallH],[w/2,0]];for(const zz of[-d/2,d/2])for(const [xx,yy] of cross)P.push(xx,yy,zz);const I=[0,1,2,0,2,3,0,3,4,5,7,6,5,8,7,5,9,8,0,5,6,0,6,1,1,6,7,1,7,2,2,7,8,2,8,3,3,8,9,3,9,4,4,9,5,4,5,0];const e=customMesh(name,P,I,M.dark,[x,0,z]);addSolid([x,wallH/2,z],[w,wallH,d]);for(let zz=-d/2+1;zz<d/2;zz+=1.15){box(name+' ribL',[x-w/2-.035,wallH*.52,z+zz],[.08,wallH*.92,.07],M.steel);box(name+' ribR',[x+w/2+.035,wallH*.52,z+zz],[.08,wallH*.92,.07],M.steel)}box(name+' rollup',[x,2.1,z+d/2+.04],[4.4,4.2,.12],M.steel);for(let yy=.35;yy<4;yy+=.34)box(name+' door slat',[x,yy,z+d/2+.12],[4.15,.035,.05],M.dark);for(const sx of[-w*.32,w*.32])box(name+' vent',[x+sx,wallH*.72,z+d/2+.13],[1.35,.65,.08],M.rust);return e}
function container(name,p,color){box(name,p,[7.3,2.6,2.55],color,true);for(let x=-3.25;x<=3.25;x+=.47){box(name+' ribF',[p[0]+x,p[1],p[2]+1.30],[.055,2.25,.07],M.steel);box(name+' ribB',[p[0]+x,p[1],p[2]-1.30],[.055,2.25,.07],M.steel)}for(const xx of[-3.52,3.52])for(const yy of[-1.05,1.05])for(const zz of[-1.22,1.22])box(name+' corner',[p[0]+xx,p[1]+yy,p[2]+zz],[.18,.18,.18],M.steel);for(const xx of[-.72,.72])cyl(name+' doorbar',[p[0]+3.67,p[1],p[2]+xx],[.055,2.18,.055],M.steel,false,[0,0,90])}
function fence(name,x,z,len,rotY=0){const r=new pc.Entity(name);r.setPosition(x,0,z);r.setEulerAngles(0,rotY,0);app.root.addChild(r);const mk=(p,s)=>{const e=box('fence part',[0,0,0],[.1,.1,.1],M.steel);e.reparent(r);e.setLocalPosition(...p);e.setLocalScale(...s)};for(let i=-len/2;i<=len/2;i+=2.4)mk([i,1.25,0],[.09,2.5,.09]);for(const y of[.25,1.15,2.1])mk([0,y,0],[len,.035,.035]);for(let i=-len/2;i<len/2;i+=.55)mk([i,1.2,0],[.018,2,.018])}
function pallet(x,z,rot=0){const r=new pc.Entity('Pallet');r.setPosition(x,.13,z);r.setEulerAngles(0,rot,0);app.root.addChild(r);for(let i=-2;i<=2;i++){const p=box('plank',[0,0,0],[.1,.1,.1],M.wood);p.reparent(r);p.setLocalPosition(i*.28,.1,0);p.setLocalScale(.18,.12,1.1)}for(const zz of[-.42,0,.42]){const q=box('brace',[0,0,0],[.1,.1,.1],M.wood);q.reparent(r);q.setLocalPosition(0,0,zz);q.setLocalScale(1.5,.16,.14)}}
function lamp(x,z){cyl('lamp post',[x,2.8,z],[.09,5.6,.09],M.steel);box('lamp arm',[x+.55,5.55,z],[1.1,.07,.07],M.steel);box('lamp',[x+1,5.42,z],[.55,.12,.28],M.glow);const l=new pc.Entity('yard lamp');l.addComponent('light',{type:'omni',color:new pc.Color(.85,.72,.48),intensity:1.1,range:11,castShadows:false});l.setPosition(x+1,5.2,z);app.root.addChild(l)}
function pipeRun(x,z,len){for(let i=0;i<3;i++){cyl('pipe',[x+i*.42,1.35,z],[.12,len,.12],i===0?M.rust:M.steel,false,[90,0,0]);for(let j=-len/2;j<=len/2;j+=4)cyl('collar',[x+i*.42,1.35,z+j],[.16,.08,.16],M.dark,false,[90,0,0])}}

box('yard ground',[0,-.24,0],[62,.48,72],M.asphalt);box('loading apron',[0,-.02,-18],[25,.08,21],M.concrete);warehouse('Warehouse 07',-16,-21,19,24,6.4,3.2);warehouse('Maintenance Shed',18,-28,13,15,4.8,2.3);
container('Cobalt',[-8,1.3,3],M.blue);container('Oxide',[0,1.3,3],M.red);container('Olive',[8,1.3,3],M.green);container('Stack base',[18,1.3,-4],M.red);container('Stack upper',[18,3.9,-4],M.blue);addSolid([18,2.6,-4],[7.3,5.2,2.55]);
fence('west fence',-29,0,66,90);fence('east fence',29,0,66,90);fence('south gate A',-18,-35,20);fence('south gate B',18,-35,20);
for(const p of[[-21,8],[-18,9.3],[13,9],[16,10.4],[-4,-10],[6,-12]])pallet(p[0],p[1],(p[0]*13)%90);
for(let i=0;i<7;i++){const x=-22+(i%4)*1.2,z=13+Math.floor(i/4)*1.25;cyl('barrel',[x,.55,z],[.62,1.1,.62],i%3===0?M.yellow:M.rust)}pipeRun(25,-17,17);lamp(-24,18);lamp(24,16);lamp(-4,-14);
for(let z=-30;z<29;z+=5)box('lane dash',[-.7,.015,z],[.12,.025,2.2],M.yellow);for(const p of[[12,-13,2.2,1],[-17,15,1.6,.7],[4,19,1.2,.6]])box('puddle',[p[0],.015,p[1]],[p[2],.012,p[3]],M.glass);for(const p of[[-12,-6],[13,-17],[21,4],[-22,19]]){box('crate',[p[0],.55,p[1]],[1.1,1.1,1.1],M.wood,true);for(let y=.1;y<1.05;y+=.32)box('crate band',[p[0],y,p[1]+.56],[1.08,.06,.05],M.steel)}
for(const x of[20,27])box('crane leg',[x,7,-33],[.55,14,.55],M.yellow);box('crane beam',[23.5,14,-33],[15,.55,.55],M.yellow);box('crane boom',[15.7,15.4,-33],[20,.28,.28],M.yellow,false,[0,0,-7]);
const objective=sphere('Encrypted drive',[13,.75,-18],[.48,.48,.48],M.glow),exBeacon=cyl('Extraction beacon',[0,1.65,29],[.22,3.3,.22],M.glow);exBeacon.enabled=false;

const weaponRoot=new pc.Entity('WeaponRoot');camera.addChild(weaponRoot);weaponRoot.setLocalPosition(.34,-.39,-.72);weaponRoot.setLocalEulerAngles(-4,180,0);const wfb=new pc.Entity('Fallback rifle');weaponRoot.addChild(wfb);
function vm(type,p,s,m,rot=null){const e=new pc.Entity('vm');e.addComponent('render',{type,castShadows:false,receiveShadows:false});e.render.material=m;e.setLocalPosition(...p);e.setLocalScale(...s);if(rot)e.setLocalEulerAngles(...rot);wfb.addChild(e)}
vm('box',[0,0,0],[.34,.13,.52],M.dark);vm('box',[0,.015,-.45],[.26,.12,.45],M.steel);vm('cylinder',[0,.015,-.94],[.045,.62,.045],M.steel,[90,0,0]);vm('box',[0,-.17,-.05],[.16,.35,.18],M.dark,[8,0,0]);vm('box',[0,.02,.43],[.25,.15,.35],M.dark);vm('box',[0,.15,-.12],[.12,.10,.20],M.steel);vm('cylinder',[0,.18,-.18],[.08,.18,.08],M.glass,[90,0,0]);let weaponModel=wfb;
app.assets.loadFromUrl('https://raw.githubusercontent.com/petroulacl/fps-asset-kit/main/weapons/flat_guns_west/Flat%20Guns%20West/GLB/Rifle_Assault_West.glb','container',(err,a)=>{if(err||!a?.resource)return;try{const e=a.resource.instantiateRenderEntity();weaponRoot.addChild(e);e.setLocalScale(.46,.46,.46);e.setLocalPosition(.04,-.1,-.1);e.setLocalEulerAngles(0,90,0);wfb.enabled=false;weaponModel=e}catch(ex){console.warn(ex)}});
const muzzle=sphere('muzzle',[0,0,0],[.14,.14,.14],M.glow);muzzle.reparent(weaponRoot);muzzle.setLocalPosition(0,.02,-1.24);muzzle.enabled=false;const shotAudio=new Audio('https://raw.githubusercontent.com/petroulacl/fps-asset-kit/main/sfx/gunshots/game_gunshot.wav');shotAudio.preload='auto';shotAudio.volume=.45;

function createEnemy(x,z,i){const root=new pc.Entity('Raider '+i);root.setPosition(x,0,z);app.root.addChild(root);const fallback=new pc.Entity('fallbackBody'),gear=new pc.Entity('tacticalGear');root.addChild(fallback);root.addChild(gear);const mk=(parent,type,p,s,m,rot=null)=>{const e=new pc.Entity('part');e.addComponent('render',{type,castShadows:true,receiveShadows:true});e.render.material=m;e.setLocalPosition(...p);e.setLocalScale(...s);if(rot)e.setLocalEulerAngles(...rot);parent.addChild(e)};mk(fallback,'capsule',[0,1.35,0],[.48,.72,.34],M.cloth);mk(fallback,'sphere',[0,2.08,0],[.42,.46,.42],M.skin);mk(fallback,'capsule',[-.43,1.35,-.06],[.17,.52,.17],M.cloth,[20,0,-7]);mk(fallback,'capsule',[.43,1.35,-.06],[.17,.52,.17],M.cloth,[20,0,7]);mk(fallback,'capsule',[-.17,.55,0],[.19,.64,.19],M.dark);mk(fallback,'capsule',[.17,.55,0],[.19,.64,.19],M.dark);mk(gear,'sphere',[0,2.19,-.02],[.49,.28,.49],M.dark);mk(gear,'box',[0,1.43,-.24],[.56,.58,.18],M.green);mk(gear,'box',[0,1.42,.29],[.50,.58,.18],M.dark);mk(gear,'box',[.28,1.42,-.48],[.72,.09,.10],M.steel);enemies.push({root,fallback,gear,body:null,hp:100,dead:false,cool:.7+Math.random(),phase:Math.random()*6.28})}
[[-10,-3],[10,-7],[-9,-19],[18,-17],[-18,11]].forEach((p,i)=>createEnemy(p[0],p[1],i+1));
app.assets.loadFromUrl('https://raw.githubusercontent.com/UMRAM-Bilkent/supine-human-model/main/assets/human_posed.glb','container',(err,a)=>{if(err||!a?.resource)return;enemies.forEach(e=>{try{const body=a.resource.instantiateRenderEntity();e.root.addChild(body);body.setLocalScale(1,1,1);body.setLocalEulerAngles(0,180,0);e.fallback.enabled=false;e.body=body}catch(_){}})});

function collides(x,z,r=.38){return solids.some(s=>x+r>s.minX&&x-r<s.maxX&&z+r>s.minZ&&z-r<s.maxZ)}
function blocked(ax,az,bx,bz){const n=Math.ceil(Math.hypot(bx-ax,bz-az)/.9);for(let i=1;i<n;i++){const t=i/n;if(collides(ax+(bx-ax)*t,az+(bz-az)*t,.05))return true}return false}
function raySphere(o,d,c,r){const oc=new pc.Vec3().sub2(o,c),b=oc.dot(d),q=oc.dot(oc)-r*r,disc=b*b-q;if(disc<0)return null;const t=-b-Math.sqrt(disc);return t>0?t:null}
function toast(t){const e=$('#toast');if(!e)return;e.textContent=t;e.classList.remove('on');void e.offsetWidth;e.classList.add('on')}
function hitMarker(head=false){const e=$('#hit-marker');if(!e)return;e.textContent=head?'✦':'×';e.classList.remove('flash');void e.offsetWidth;e.classList.add('flash')}
function burst(p,count=7){for(let i=0;i<count;i++){const q=sphere('spark',[p.x,p.y,p.z],[.035,.035,.035],M.glow);fx.push({e:q,v:new pc.Vec3((Math.random()-.5)*2,Math.random()*.9+.25,(Math.random()-.5)*2),life:.28+Math.random()*.2})}}
function nearestAimTarget(){const o=camera.getPosition(),f=camera.forward;let best=null,bestScore=.12;for(const e of enemies){if(e.dead)continue;const c=e.root.getPosition().clone();c.y+=1.55;const v=c.clone().sub(o),dist=v.length();v.normalize();const dot=f.dot(v),score=(1-dot)+dist*.0007;if(dot>.965&&dist<40&&!blocked(o.x,o.z,c.x,c.z)&&score<bestScore){bestScore=score;best=e}}return best}
function aimAssist(dt){if(!state.ads)return;const e=nearestAimTarget();if(!e)return;const p=player.getPosition(),t=e.root.getPosition(),dx=t.x-p.x,dz=t.z-p.z,desired=Math.atan2(-dx,-dz)*pc.math.RAD_TO_DEG,dy=t.y+1.55-(p.y+1.67),pitch=-Math.atan2(dy,Math.hypot(dx,dz))*pc.math.RAD_TO_DEG;let yd=((desired-state.yaw+540)%360)-180;state.yaw+=yd*Math.min(1,dt*3.2);state.pitch+=(pitch-state.pitch)*Math.min(1,dt*2.7)}
function shoot(){if(state.mode!=='raid'||state.reload>0||state.fireCd>0)return;if(state.ammo<=0){toast('MAGAZINE EMPTY · RLD');return}state.ammo--;state.fireCd=.105;muzzle.enabled=true;setTimeout(()=>muzzle.enabled=false,48);try{const a=shotAudio.cloneNode();a.volume=.46;a.play().catch(()=>{})}catch(_){}const o=camera.getPosition().clone(),d=camera.forward.clone();let best=null,bestT=Infinity,head=false,point=null;for(const e of enemies){if(e.dead)continue;const rp=e.root.getPosition(),hc=new pc.Vec3(rp.x,rp.y+2,rp.z),bc=new pc.Vec3(rp.x,rp.y+1.25,rp.z),th=raySphere(o,d,hc,.34),tb=raySphere(o,d,bc,.62);let t=null,h=false;if(th&&(tb===null||th<tb)){t=th;h=true}else if(tb)t=tb;if(t&&t<bestT){const hp=o.clone().add(d.clone().mulScalar(t));if(!blocked(o.x,o.z,hp.x,hp.z)){best=e;bestT=t;head=h;point=hp}}}if(best){best.hp-=head?82:38;hitMarker(head);burst(point,head?10:6);if(best.hp<=0){best.dead=true;state.kills++;toast(head?'HEADSHOT · HOSTILE DOWN':'HOSTILE DOWN');best.root.rotateLocal(0,0,78);setTimeout(()=>best.root.enabled=false,750)}}updateHud()}
function reload(){if(state.mode!=='raid'||state.reload>0||state.ammo>=30||state.reserve<=0)return;state.reload=1.55;state.firing=false;toast('RELOADING')}
function damage(a){if(state.shield>0||state.mode!=='raid')return;let d=a;if(state.armor>0){const ab=Math.min(state.armor,d*.72);state.armor-=ab;d-=ab*.62}state.hp=Math.max(0,state.hp-d);state.flash=.65;if(state.hp<=0)endRaid(false);updateHud()}
function interact(){if(state.mode!=='raid')return;if(state.interact==='objective'){state.objective=true;objective.enabled=false;exBeacon.enabled=true;toast('DRIVE SECURED · EXTRACT NORTH GATE')}else if(state.interact==='extract')endRaid(true)}
function ensureHudExtras(){if(!$('#nav-hint')){const n=document.createElement('div');n.id='nav-hint';n.className='nav-hint glass';n.innerHTML='<b id="nav-title">DRIVE</b><span id="nav-distance">--m</span><small id="nav-arrow">▲</small>';hud.appendChild(n)}if(!$('#interact-prompt')){const n=document.createElement('div');n.id='interact-prompt';n.className='interact-prompt hidden';hud.appendChild(n)}if(!$('#reload-progress')){const n=document.createElement('div');n.id='reload-progress';n.className='reload-progress hidden';n.innerHTML='<span></span>';hud.appendChild(n)}}ensureHudExtras();
function nav(){if(state.mode!=='raid')return;const p=player.getPosition(),target=state.objective?exBeacon.getPosition():objective.getPosition(),dx=target.x-p.x,dz=target.z-p.z,dist=Math.hypot(dx,dz);$('#nav-title').textContent=state.objective?'EXTRACT':'DRIVE';$('#nav-distance').textContent=Math.ceil(dist)+'m';const bearing=Math.atan2(-dx,-dz)*pc.math.RAD_TO_DEG,rel=((bearing-state.yaw+540)%360)-180;$('#nav-arrow').style.transform=`rotate(${rel}deg)`;state.interact=null;const prompt=$('#interact-prompt');if(!state.objective&&dist<2.2){state.interact='objective';prompt.textContent='USE · SECURE ENCRYPTED DRIVE';prompt.classList.remove('hidden')}else if(state.objective&&dist<2.7){state.interact='extract';prompt.textContent='USE · EXTRACT';prompt.classList.remove('hidden')}else prompt.classList.add('hidden')}
function updateHud(){const set=(id,v)=>{const e=$(id);if(e)e.textContent=v};set('#ammo',state.ammo);set('#reserve',state.reserve);set('#hp',Math.ceil(state.hp));set('#armor',Math.ceil(state.armor));set('#stamina',Math.ceil(state.stamina));const m=Math.floor(Math.max(0,state.raidTime)/60),s=Math.floor(Math.max(0,state.raidTime)%60);set('#raid-timer',String(m).padStart(2,'0')+':'+String(s).padStart(2,'0'));const sh=$('#shield');if(sh){if(state.shield>0){sh.classList.remove('hidden');sh.textContent='INSERTION SHIELD · '+state.shield.toFixed(1)}else sh.classList.add('hidden')}const df=$('#damage-flash');if(df)df.style.opacity=Math.min(.7,state.flash).toFixed(2);const rp=$('#reload-progress');if(rp){if(state.reload>0){rp.classList.remove('hidden');rp.querySelector('span').style.width=((1-state.reload/1.55)*100)+'%'}else rp.classList.add('hidden')}nav()}
function resetRaid(){Object.assign(state,{hp:100,armor:60,stamina:100,ammo:30,reserve:120,reload:0,raidTime:720,shield:7,ads:false,firing:false,fireCd:0,yaw:180,pitch:-2,moveX:0,moveY:0,objective:false,kills:0,flash:0,interact:null});player.setPosition(0,0,24);player.setEulerAngles(0,180,0);camera.setLocalEulerAngles(-2,0,0);objective.enabled=true;exBeacon.enabled=false;const pos=[[-10,-3],[10,-7],[-9,-19],[18,-17],[-18,11]];enemies.forEach((e,i)=>{e.hp=100;e.dead=false;e.cool=.8+Math.random();e.root.enabled=true;e.root.setPosition(pos[i][0],0,pos[i][1]);e.root.setEulerAngles(0,0,0)});$('#objective').textContent='OBJECTIVE · Secure encrypted drive';updateHud()}
function endRaid(ok){if(state.mode!=='raid')return;state.mode='result';hud.classList.add('hidden');controls.classList.add('hidden');result.classList.add('screen-on');$('#result-title').textContent=ok?'EXTRACTION SUCCESSFUL':'OPERATOR LOST';$('#result-copy').textContent=ok?`Drive recovered · ${state.kills} hostiles eliminated · kit returned.`:`Harbor Yard claimed your operator after ${state.kills} kills. Deployed kit lost.`}

const pad=$('#move-pad'),knob=$('#move-knob');let movePointer=null;function moveInput(e){const r=pad.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,lim=r.width*.31;let x=e.clientX-cx,y=e.clientY-cy,mag=Math.hypot(x,y);if(mag>lim){x*=lim/mag;y*=lim/mag}state.moveX=x/lim;state.moveY=-y/lim;knob.style.transform=`translate(${x}px,${y}px)`}pad.addEventListener('pointerdown',e=>{e.preventDefault();movePointer=e.pointerId;pad.setPointerCapture(e.pointerId);moveInput(e)});pad.addEventListener('pointermove',e=>{if(e.pointerId===movePointer){e.preventDefault();moveInput(e)}});function stopMove(e){if(e.pointerId!==movePointer)return;movePointer=null;state.moveX=state.moveY=0;knob.style.transform='translate(0,0)'}pad.addEventListener('pointerup',stopMove);pad.addEventListener('pointercancel',stopMove);
const look=$('#look-zone');let lookPointer=null,lx=0,ly=0;look.addEventListener('pointerdown',e=>{if(e.target!==look)return;e.preventDefault();lookPointer=e.pointerId;lx=e.clientX;ly=e.clientY;look.setPointerCapture(e.pointerId)});look.addEventListener('pointermove',e=>{if(e.pointerId!==lookPointer)return;e.preventDefault();state.yaw-=(e.clientX-lx)*.145;state.pitch=Math.max(-68,Math.min(58,state.pitch-(e.clientY-ly)*.115));lx=e.clientX;ly=e.clientY});look.addEventListener('pointerup',e=>{if(e.pointerId===lookPointer)lookPointer=null});look.addEventListener('pointercancel',e=>{if(e.pointerId===lookPointer)lookPointer=null});
const fire=$('#fire-btn');fire.addEventListener('pointerdown',e=>{e.preventDefault();state.firing=true;fire.setPointerCapture(e.pointerId);shoot()});['pointerup','pointercancel'].forEach(t=>fire.addEventListener(t,e=>{e.preventDefault();state.firing=false}));$('#ads-btn').addEventListener('pointerdown',e=>{e.preventDefault();state.ads=!state.ads;$('#ads-btn').classList.toggle('active',state.ads)});$('#reload-btn').addEventListener('pointerdown',e=>{e.preventDefault();reload()});$('#use-btn').addEventListener('pointerdown',e=>{e.preventDefault();interact()});
canvas.addEventListener('click',()=>{if(state.mode==='raid'&&!pc.platform.touch)canvas.requestPointerLock?.()});document.addEventListener('mousemove',e=>{if(document.pointerLockElement===canvas&&state.mode==='raid'){state.yaw-=e.movementX*.10;state.pitch=Math.max(-68,Math.min(58,state.pitch-e.movementY*.085))}});document.addEventListener('mousedown',e=>{if(state.mode==='raid'&&e.button===0){state.firing=true;shoot()}if(state.mode==='raid'&&e.button===2)state.ads=true});document.addEventListener('mouseup',e=>{if(e.button===0)state.firing=false;if(e.button===2)state.ads=false});document.addEventListener('keydown',e=>{if(e.code==='KeyR')reload();if(e.code==='KeyE')interact()});
function keys(){let x=0,y=0;if(app.keyboard.isPressed(pc.KEY_A))x--;if(app.keyboard.isPressed(pc.KEY_D))x++;if(app.keyboard.isPressed(pc.KEY_W))y++;if(app.keyboard.isPressed(pc.KEY_S))y--;return{x,y}}
function slideMove(dx,dz){const p=player.getPosition();if(!collides(p.x+dx,p.z,.40))player.setPosition(p.x+dx,0,p.z);const q=player.getPosition();if(!collides(q.x,q.z+dz,.40))player.setPosition(q.x,0,q.z+dz)}
app.on('update',dt=>{for(let i=fx.length-1;i>=0;i--){const f=fx[i];f.life-=dt;if(f.life<=0){f.e.destroy();fx.splice(i,1);continue}f.v.y-=3.8*dt;f.e.translate(f.v.x*dt,f.v.y*dt,f.v.z*dt);f.e.setLocalScale(f.life*.15,f.life*.15,f.life*.15)}if(state.mode!=='raid')return;state.raidTime-=dt;state.shield=Math.max(0,state.shield-dt);state.fireCd=Math.max(0,state.fireCd-dt);state.flash=Math.max(0,state.flash-dt*2);if(state.raidTime<=0){endRaid(false);return}if(state.reload>0){state.reload-=dt;weaponRoot.setLocalEulerAngles(-17,180,8);if(state.reload<=0){const n=Math.min(30-state.ammo,state.reserve);state.ammo+=n;state.reserve-=n;toast('MAGAZINE SEATED')}}else weaponRoot.setLocalEulerAngles(-4,180,0);if(state.firing)shoot();const k=keys();let mx=Math.abs(state.moveX)>.025?state.moveX:k.x,my=Math.abs(state.moveY)>.025?state.moveY:k.y,l=Math.hypot(mx,my);if(l>1){mx/=l;my/=l}const sprint=l>.82&&state.stamina>5&&!state.ads,speed=sprint?5.7:state.ads?2.7:4;if(sprint)state.stamina=Math.max(0,state.stamina-dt*15);else state.stamina=Math.min(100,state.stamina+dt*12);aimAssist(dt);const yr=state.yaw*pc.math.DEG_TO_RAD,fxv=-Math.sin(yr),fz=-Math.cos(yr),rx=Math.cos(yr),rz=-Math.sin(yr);slideMove((rx*mx+fxv*my)*speed*dt,(rz*mx+fz*my)*speed*dt);player.setEulerAngles(0,state.yaw,0);camera.setLocalEulerAngles(state.pitch,0,0);const fov=state.ads?48:68;camera.camera.fov+=(fov-camera.camera.fov)*Math.min(1,dt*10);const target=state.ads?new pc.Vec3(.01,-.15,-.48):new pc.Vec3(.34,-.39,-.72),wp=weaponRoot.getLocalPosition(),sm=Math.min(1,dt*12);weaponRoot.setLocalPosition(wp.x+(target.x-wp.x)*sm,wp.y+(target.y-wp.y)*sm,wp.z+(target.z-wp.z)*sm);const pp=player.getPosition();for(const e of enemies){if(e.dead||!e.root.enabled)continue;e.cool-=dt;e.phase+=dt*5.3;const ep=e.root.getPosition(),dx=pp.x-ep.x,dz=pp.z-ep.z,dist=Math.hypot(dx,dz),los=dist<30&&!blocked(ep.x,ep.z,pp.x,pp.z);if(los){e.root.setEulerAngles(0,Math.atan2(dx,dz)*pc.math.RAD_TO_DEG,0);if(dist>8.2){const vx=dx/dist*dt*1.15,vz=dz/dist*dt*1.15;if(!collides(ep.x+vx,ep.z,.34))e.root.translate(vx,0,0);const q=e.root.getPosition();if(!collides(q.x,q.z+vz,.34))e.root.translate(0,0,vz);if(e.fallback.enabled)e.fallback.setLocalPosition(0,Math.sin(e.phase)*.025,0)}if(dist<23&&e.cool<=0){e.cool=1.15+Math.random()*.75;const acc=Math.max(.10,.50-dist*.014);if(Math.random()<acc)damage(5+Math.random()*7)}}}updateHud()});

$('#deploy-btn').addEventListener('click',()=>{menu.classList.remove('screen-on');brief.classList.add('screen-on');state.mode='brief'});$('#begin-btn').addEventListener('click',()=>{brief.classList.remove('screen-on');hud.classList.remove('hidden');controls.classList.remove('hidden');resetRaid();state.mode='raid';canvas.focus()});$('#return-btn').addEventListener('click',()=>{result.classList.remove('screen-on');hud.classList.add('hidden');controls.classList.add('hidden');menu.classList.add('screen-on');state.mode='menu'});document.querySelectorAll('.stash-item').forEach(b=>b.addEventListener('click',()=>toast((b.dataset.name||'GEAR').toUpperCase()+' · INSPECTED')));
const bs=document.querySelector('.brief-stats');if(bs)bs.innerHTML='<span>INSERTION SHIELD <b>7s</b></span><span>HOSTILES <b>5</b></span><span>ROUTE <b>~90m</b></span>';const bp=document.querySelector('#brief p');if(bp)bp.textContent='Push through the working yard, secure the encrypted drive inside the loading apron, then return to North Gate. HUD navigation is active.';
stage('Harbor Yard ready · tactical systems online');setTimeout(()=>{if(boot){boot.style.opacity='0';boot.style.transition='opacity .35s';setTimeout(()=>boot.remove(),380)}state.mode='menu';window.__BLACKSITE_READY__=true},650);
}catch(err){console.error(err);window.__BLACKSITE_BOOT_ERROR__=String(err?.message||err);const c=document.getElementById('boot-copy');if(c){c.textContent='BOOT ERROR · '+window.__BLACKSITE_BOOT_ERROR__.slice(0,160);c.style.color='#ff9f80'}}
})();